# Generated by Django 6.0.3 on 2026-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_practicesheet_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmastery',
            name='lapses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topicmastery',
            name='difficulty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='topicmastery',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
