# Generated by Django 5.2.13 on 2026-04-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_topicmastery_lapses_topicmastery_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='encompassings',
            field=models.ManyToManyField(blank=True, help_text='Simpler topics that are implicitly practiced when this topic is practiced', related_name='encompassed_by', to='questions.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Topics that must be known before learning this topic', related_name='prerequisite_for', to='questions.topic'),
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this specific bit of knowledge')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to='questions.topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='knowledge_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.knowledgepoint'),
        ),
    ]
