# Generated by Django 5.2.13 on 2026-05-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_current_xp_user_first_name_user_last_name_and_more'),
        ('accounts', '0002_user_current_xp_user_last_practice_date_and_more'),
    ]

    operations = [
    ]
