# Generated by Django 5.2.13 on 2026-05-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260527_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_at',
            new_name='date_joined',
        ),
    ]
