# Generated by Django 5.2.13 on 2026-05-06 14:21

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', accounts.models.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name='LearnerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', accounts.models.LearnerManager()),
            ],
        ),
    ]
