# Generated by Django 5.2.13 on 2026-07-01 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("review_reminder", "Review reminder")], max_length=32
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email")], default="email", max_length=16
                    ),
                ),
                (
                    "sent_date",
                    models.DateField(
                        help_text="UTC date this notification was sent (daily idempotency key)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "sent_date"],
                        name="notificatio_user_id_b34e78_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "kind", "channel", "sent_date"),
                        name="uniq_notification_per_user_kind_channel_day",
                    )
                ],
            },
        ),
    ]
