export interface TopicItem {
  id: string;
  nameKey: string;
  icon: string;
  progress: number;
  questionsTotal: number;
  questionsDue: number;
  lastReviewed?: string;
  state: "new" | "learning" | "review" | "mastered";
  /** FSRS retrievability 0-1: lower = more urgent (UC-08 Step 4) */
  memory: number;
  /** Scaffolding tier 1–3 (UC-08 Step 5) */
  tier: 1 | 2 | 3;
  /** Next scheduled review date label */
  nextReview?: string;
}

export interface TopicCategory {
  id: string;
  nameKey: string;
  icon: string;
  topics: TopicItem[];
}

// Mock topic data — includes memory & tier for UC-08
export const TOPIC_CATEGORIES: TopicCategory[] = [
  {
    id: "logic",
    nameKey: "topics:logic.title",
    icon: "🔢",
    topics: [
      {
        id: "propositional",
        nameKey: "topics:logic.propositional",
        icon: "→",
        progress: 75,
        questionsTotal: 20,
        questionsDue: 3,
        lastReviewed: "2 days ago",
        state: "review",
        memory: 0.62,
        tier: 2,
        nextReview: "today",
      },
      {
        id: "predicates",
        nameKey: "topics:logic.predicates",
        icon: "∀",
        progress: 45,
        questionsTotal: 15,
        questionsDue: 5,
        lastReviewed: "1 week ago",
        state: "learning",
        memory: 0.38,
        tier: 1,
        nextReview: "today",
      },
      {
        id: "quantifiers",
        nameKey: "topics:logic.quantifiers",
        icon: "∃",
        progress: 20,
        questionsTotal: 12,
        questionsDue: 8,
        state: "learning",
        memory: 0.25,
        tier: 1,
        nextReview: "today",
      },
      {
        id: "proofs",
        nameKey: "topics:logic.proofTechniques",
        icon: "⊢",
        progress: 0,
        questionsTotal: 18,
        questionsDue: 0,
        state: "new",
        memory: 1.0,
        tier: 3,
      },
    ],
  },
  {
    id: "sets",
    nameKey: "topics:sets.title",
    icon: "∪",
    topics: [
      {
        id: "operations",
        nameKey: "topics:sets.operations",
        icon: "∩",
        progress: 90,
        questionsTotal: 16,
        questionsDue: 1,
        lastReviewed: "1 day ago",
        state: "mastered",
        memory: 0.92,
        tier: 2,
        nextReview: "in 5 days",
      },
      {
        id: "venn",
        nameKey: "topics:sets.vennDiagrams",
        icon: "◯",
        progress: 60,
        questionsTotal: 10,
        questionsDue: 2,
        lastReviewed: "3 days ago",
        state: "review",
        memory: 0.55,
        tier: 1,
        nextReview: "today",
      },
      {
        id: "power",
        nameKey: "topics:sets.powerSets",
        icon: "P",
        progress: 30,
        questionsTotal: 12,
        questionsDue: 6,
        state: "learning",
        memory: 0.3,
        tier: 2,
        nextReview: "today",
      },
      {
        id: "cartesian",
        nameKey: "topics:sets.cartesianProduct",
        icon: "×",
        progress: 0,
        questionsTotal: 14,
        questionsDue: 0,
        state: "new",
        memory: 1.0,
        tier: 1,
      },
    ],
  },
  {
    id: "relations",
    nameKey: "topics:relations.title",
    icon: "≡",
    topics: [
      {
        id: "properties",
        nameKey: "topics:relations.properties",
        icon: "R",
        progress: 55,
        questionsTotal: 18,
        questionsDue: 4,
        lastReviewed: "4 days ago",
        state: "review",
        memory: 0.48,
        tier: 2,
        nextReview: "today",
      },
      {
        id: "equivalence",
        nameKey: "topics:relations.equivalence",
        icon: "~",
        progress: 25,
        questionsTotal: 14,
        questionsDue: 7,
        state: "learning",
        memory: 0.22,
        tier: 2,
        nextReview: "today",
      },
      {
        id: "partial",
        nameKey: "topics:relations.partialOrders",
        icon: "≤",
        progress: 0,
        questionsTotal: 16,
        questionsDue: 0,
        state: "new",
        memory: 1.0,
        tier: 3,
      },
      {
        id: "functions",
        nameKey: "topics:relations.functions",
        icon: "f",
        progress: 10,
        questionsTotal: 20,
        questionsDue: 10,
        state: "learning",
        memory: 0.15,
        tier: 1,
        nextReview: "today",
      },
    ],
  },
  {
    id: "combinatorics",
    nameKey: "topics:combinatorics.title",
    icon: "📊",
    topics: [
      {
        id: "counting",
        nameKey: "topics:combinatorics.counting",
        icon: "#",
        progress: 80,
        questionsTotal: 14,
        questionsDue: 2,
        lastReviewed: "2 days ago",
        state: "review",
        memory: 0.7,
        tier: 1,
        nextReview: "tomorrow",
      },
      {
        id: "permutations",
        nameKey: "topics:combinatorics.permutations",
        icon: "P",
        progress: 65,
        questionsTotal: 12,
        questionsDue: 3,
        lastReviewed: "5 days ago",
        state: "review",
        memory: 0.5,
        tier: 2,
        nextReview: "tomorrow",
      },
      {
        id: "combinations",
        nameKey: "topics:combinatorics.combinations",
        icon: "C",
        progress: 40,
        questionsTotal: 12,
        questionsDue: 5,
        state: "learning",
        memory: 0.35,
        tier: 2,
        nextReview: "in 2 days",
      },
      {
        id: "pigeonhole",
        nameKey: "topics:combinatorics.pigeonhole",
        icon: "🕊",
        progress: 0,
        questionsTotal: 8,
        questionsDue: 0,
        state: "new",
        memory: 1.0,
        tier: 3,
      },
    ],
  },
  {
    id: "graphTheory",
    nameKey: "topics:graphTheory.title",
    icon: "🔗",
    topics: [
      {
        id: "basics",
        nameKey: "topics:graphTheory.basics",
        icon: "G",
        progress: 50,
        questionsTotal: 16,
        questionsDue: 4,
        lastReviewed: "3 days ago",
        state: "review",
        memory: 0.52,
        tier: 1,
        nextReview: "today",
      },
      {
        id: "paths",
        nameKey: "topics:graphTheory.paths",
        icon: "→",
        progress: 35,
        questionsTotal: 14,
        questionsDue: 6,
        state: "learning",
        memory: 0.28,
        tier: 2,
        nextReview: "today",
      },
      {
        id: "trees",
        nameKey: "topics:graphTheory.trees",
        icon: "🌳",
        progress: 15,
        questionsTotal: 12,
        questionsDue: 8,
        state: "learning",
        memory: 0.18,
        tier: 2,
        nextReview: "today",
      },
      {
        id: "planarity",
        nameKey: "topics:graphTheory.planarity",
        icon: "◇",
        progress: 0,
        questionsTotal: 10,
        questionsDue: 0,
        state: "new",
        memory: 1.0,
        tier: 3,
      },
    ],
  },
  {
    id: "numberTheory",
    nameKey: "topics:numberTheory.title",
    icon: "🔢",
    topics: [
      {
        id: "divisibility",
        nameKey: "topics:numberTheory.divisibility",
        icon: "|",
        progress: 70,
        questionsTotal: 14,
        questionsDue: 2,
        lastReviewed: "1 day ago",
        state: "review",
        memory: 0.78,
        tier: 1,
        nextReview: "in 3 days",
      },
      {
        id: "modular",
        nameKey: "topics:numberTheory.modularArithmetic",
        icon: "%",
        progress: 45,
        questionsTotal: 16,
        questionsDue: 5,
        state: "learning",
        memory: 0.33,
        tier: 2,
        nextReview: "today",
      },
      {
        id: "gcd",
        nameKey: "topics:numberTheory.gcd",
        icon: "÷",
        progress: 85,
        questionsTotal: 10,
        questionsDue: 1,
        lastReviewed: "2 days ago",
        state: "mastered",
        memory: 0.88,
        tier: 1,
        nextReview: "in 7 days",
      },
      {
        id: "primes",
        nameKey: "topics:numberTheory.primes",
        icon: "p",
        progress: 20,
        questionsTotal: 12,
        questionsDue: 7,
        state: "learning",
        memory: 0.2,
        tier: 1,
        nextReview: "today",
      },
    ],
  },
];

/** Tier badge emoji (UC-08 Step 5) */
export const TIER_BADGE: Record<1 | 2 | 3, string> = {
  1: "🥉",
  2: "🥈",
  3: "🥇",
};
