# Generated by Django 5.2.13 on 2026-05-07 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='topics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='SubtopicMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.FloatField(default=5.0, help_text='FSRS difficulty (1–10)')),
                ('stability', models.FloatField(default=1.0, help_text='FSRS stability in days')),
                ('reps', models.IntegerField(default=0, help_text='Number of successful reviews')),
                ('lapses', models.IntegerField(default=0, help_text='Number of times forgotten')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('REVIEW', 'Review'), ('RELEARNING', 'Relearning')], default='NEW', max_length=20)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to=settings.AUTH_USER_MODEL)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='topics.subtopic')),
            ],
            options={
                'unique_together': {('learner', 'subtopic')},
            },
        ),
    ]
