# Generated by Django 5.2.13 on 2026-06-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_parent_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='parent_module',
        ),
    ]
