# Generated by Django 5.2.13 on 2026-06-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topic_parent_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicmastery',
            name='next_review',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
