# Generated by Django 5.2.13 on 2026-05-06 22:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0007_adminuser_learneruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlequestioninteraction',
            name='question',
        ),
        migrations.RemoveField(
            model_name='singlequestioninteraction',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Concept'), (2, 'Application'), (3, 'Synthesis')], default=1, help_text='1=Concept, 2=Application, 3=Synthesis'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('confidence_rating', models.IntegerField(default=3, help_text='1=Total guess, 5=Completely sure')),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questions.practicesession')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic', models.ForeignKey(default='6b63f272-e12e-49f8-86d5-5074e573526a', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='questions.topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(default='6b63f272-e12e-49f8-86d5-5074e573526a', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.subtopic'),
        ),
        migrations.CreateModel(
            name='SubtopicMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.FloatField(default=5.0, help_text='FSRS difficulty (1–10)')),
                ('stability', models.FloatField(default=1.0, help_text='FSRS stability in days')),
                ('reps', models.IntegerField(default=0, help_text='Number of successful reviews')),
                ('lapses', models.IntegerField(default=0, help_text='Number of times forgotten')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('REVIEW', 'Review'), ('RELEARNING', 'Relearning')], default='NEW', max_length=20)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='users.learner')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='questions.subtopic')),
            ],
            options={
                'unique_together': {('learner', 'subtopic')},
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SingleQuestionInteraction',
        ),
        migrations.DeleteModel(
            name='TopicMastery',
        ),
    ]
