# Generated by Django 6.0.2 on 2026-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="selected_answer_index",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="tier",
            field=models.IntegerField(
                default=1, help_text="1=Concept, 2=Application, 3=Synthesis"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="description",
            field=models.TextField(blank=True, help_text="Short summary of the topic"),
        ),
        migrations.AddField(
            model_name="topic",
            name="parent_module",
            field=models.CharField(
                blank=True, help_text="e.g. Discrete Math > Logic", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer_index",
            field=models.IntegerField(),
        ),
    ]
