# Generated by Django 6.0.3 on 2026-03-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer_selected_answer_index_question_tier_and_more'),
        ('users', '0003_rename_xp_student_total_xp_user_account_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesheet',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicmastery',
            name='difficulty',
            field=models.FloatField(default=5.0),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('adaptive', 'Adaptive'), ('quiz', 'Quiz'), ('review', 'Review')], default='adaptive', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_xp_earned', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='SingleQuestionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('confidence_rating', models.IntegerField(default=1, help_text='1=Guess, 5=Sure')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='questions.practicesession')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='PracticeSheet',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
