# Generated by Django 5.2.13 on 2026-04-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_topic_topic_encompassings_and_more'),
        ('users', '0005_alter_learner_user_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicesession',
            old_name='student',
            new_name='learner',
        ),
        migrations.RenameField(
            model_name='topicmastery',
            old_name='student',
            new_name='learner',
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together={('learner', 'topic')},
        ),
    ]
