# Generated by Django 5.2.13 on 2026-04-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_rename_student_practicesession_learner_and_more'),
        ('users', '0005_alter_learner_user_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='users.learner'),
        ),
        migrations.AlterField(
            model_name='topicmastery',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='users.learner'),
        ),
        migrations.AlterField(
            model_name='topicmastery',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
