# Generated by Django 5.2.13 on 2026-04-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_fix_state_zero_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmastery',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='lapses',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='last_review_date',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='next_review_date',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='stability',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='state',
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='mastery_level',
            field=models.FloatField(default=0.0, help_text='Mastery level from 0.0 to 100.0'),
        ),
    ]
