# Generated by Django 5.2.13 on 2026-04-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_topicmastery_difficulty_and_more'),
        ('users', '0006_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='encompassings',
        ),
        migrations.RemoveField(
            model_name='topicmastery',
            name='mastery_level',
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='memory',
            field=models.FloatField(default=0.0, help_text='Memory strength'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='next_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='rep_num',
            field=models.FloatField(default=0.0, help_text='Repetition progress'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='speed',
            field=models.FloatField(default=1.0, help_text='Student-topic learning speed'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('learned', 'Learned'), ('struggling', 'Struggling')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.learner')),
                ('topics', models.ManyToManyField(to='questions.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Encompassing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Fraction of credit passed down')),
                ('advanced_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encompasses', to='questions.topic')),
                ('simple_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encompassed_by', to='questions.topic')),
            ],
            options={
                'unique_together': {('advanced_topic', 'simple_topic')},
            },
        ),
    ]
