# Generated by Django 5.2.13 on 2026-05-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='confidence_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
