# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_questionresponse_confidence_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='selected_answer_index',
            field=models.IntegerField(null=True),
        ),
    ]
