# Generated by Django 5.2.13 on 2026-06-28 13:53

from django.db import migrations, models


def backfill_answered_at(apps, schema_editor):
    """Mark previously-answered responses as answered.

    The "already answered?" check moved from ``selected_answer_index is not None``
    to ``answered_at is not None``. Existing answered (MCQ) rows have a selected
    index but a null ``answered_at``; without this backfill they would look
    unanswered and become re-answerable. We stamp them with their session's
    completion (or start) time as a sensible historical marker.
    """
    QuestionResponse = apps.get_model("practice", "QuestionResponse")
    rows = (
        QuestionResponse.objects
        .filter(selected_answer_index__isnull=False, answered_at__isnull=True, session__isnull=False)
        .select_related("session")
    )
    to_update = []
    for row in rows.iterator():
        row.answered_at = row.session.end_time or row.session.start_time
        if row.answered_at:
            to_update.append(row)
    if to_update:
        QuestionResponse.objects.bulk_update(to_update, ["answered_at"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_alter_practicesession_learner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="grading_method",
            field=models.CharField(
                choices=[
                    ("EXACT_INDEX", "Exact choice index (MCQ)"),
                    ("CAS", "Symbolic equivalence (algebra)"),
                    ("LLM", "LLM rubric (planned)"),
                ],
                default="EXACT_INDEX",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ", "Multiple choice"),
                    ("WRITTEN", "Written (free response)"),
                ],
                default="MCQ",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="written_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_answered_at, migrations.RunPython.noop),
    ]
