# Generated by Django 5.2.13 on 2026-04-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_xp_student_total_xp_user_account_locked_until_and_more'),
    ]

    operations = [
        migrations.RenameModel(old_name='Student', new_name='Learner'),
    ]
