# Generated by Django 5.2.13 on 2026-04-18 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_student_to_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('admin', 'Admin')], default='learner', max_length=20),
        ),
    ]
